[package]
name = "restuarant"
version = "0.1.0"
authors = ["youngjuning <youngjuning@aliyun.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
